apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "personal-ovpn.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ include "personal-ovpn.name" . }}
    helm.sh/chart: {{ include "personal-ovpn.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "personal-ovpn.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "personal-ovpn.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          ports:
            - containerPort: 1194
              name: openvpn
              protocol: {{ .Values.service.protocol }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: {{ .Values.security.privileged }}
          lifecycle:
            postStart:
              exec:
                command:
                  - "sysctl"
                  - "net.ipv4.ip_forward={{ .Values.security.ipForward }}"
          volumeMounts:
            {{- if .Values.automatic.enabled }}
            - name: data
              mountPath: {{ .Values.automatic.persistence.mountPath }}
            {{- else }}
            - name: {{ .Values.secretName }}-key
              mountPath: /etc/openvpn/pki/private
            - name: {{ .Values.secretName }}-cert
              mountPath: /etc/openvpn/pki/issued
            - name: {{ .Values.secretName }}-pki
              mountPath: /etc/openvpn/pki
            - name: {{ .Values.secretName }}-conf
              mountPath: /etc/openvpn
            - name: ccd0
              mountPath: /etc/openvpn/ccd
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- if .Values.automatic.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ if .Values.automatic.persistence.existingClaim }}{{ .Values.automatic.persistence.existingClaim }}{{- else }}{{ include "personal-ovpn.name" . }}{{- end }}
        {{- else }}
        - name: {{ .Values.secretName }}-key
          secret:
            secretName: {{ .Values.secretName }}-key
            defaultMode: 0600
        - name: {{ .Values.secretName }}-cert
          secret:
            secretName: {{ .Values.secretName }}-cert
        - name: {{ .Values.secretName }}-pki
          secret:
            secretName: {{ .Values.secretName }}-pki
            defaultMode: 0600
        - name: {{ .Values.secretName }}-conf
          configMap:
            name: {{ .Values.secretName }}-conf
        - name: ccd0
          configMap:
            name: ccd0
        {{- end }}
