apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ds-files
spec:
  {{- if Values.persistence.storageClass }}
  storageClassName: {{ if (eq "-" Values.persistence.storageClass) }}""{{- else }}{{ Values.persistence.storageClass | quote }}{{- end }}
  {{- end }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size }}